### ISSUE TITLE
Bulk inserts trigger exception in mongo-db.js

### ISSUE THREAD

**Issue by mmilitzer** [tliron/mongodb-jvm#2]
Hi,

I've noticed issues when trying to do bulk inserts. Basically, multiple documents can be inserted at once with one call to insert if instead of a single document an array of documents is given as the parameter.

However doing this causes an exception in the mongo-db.js wrapper. The culprit is line 1468:

https://github.com/tliron/mongodb-jvm/blob/master/components/sincerity/libraries/scripturian/mongo-db.js#L1468

I think the problem is that with bulk inserts and an array of documents, there simply is not one "_id" field in the returned bson object (as with single document inserts). Therefore the "get" is for an undefined field and triggers an exception. In result, the "insert" does not complete correctly and it looks to the caller as if it failed.

I've now just wrapped a try/catch around l. 1468 to ignore the exception if the "_id" field does not exist but that's likely not the real fix. 

We are using an older version of the mongodb-jvm driver and mongo-db.js than what you have currently in git and so it might be that the problem is specific to our version. But from browsing the latest code here, it looks like the issue will still be present also in the latest version...

**Comment by tliron** [comment]
Thanks for taking time to investigate! However, you are looking at the wrong file. All of this has been much clarified in the 3.0 series drivers.

You have updateOne vs. [updateMany](https://github.com/tliron/mongodb-jvm/blob/master/components/sincerity/libraries/scripturian/mongodb.js#L1694), with the latter returning a specialized data structure. Additionally you have the special [bulk](https://github.com/tliron/mongodb-jvm/blob/master/components/sincerity/libraries/scripturian/mongodb.js#L1815) mode (which has existed in the 2.0 series, too).

In general, the new JS driver follows the Java driver quite closely, exactly in order to avoid such divergences in interpretation that lead to bugs. Indeed, I tried to be too clever with the old version and provide nice features beyond what the Java driver provided, but as you can see in this case, I missed several edge cases.

Your try/catch solution is probably your best bet if you are sticking to the old driver, or else you can go ahead and path it yourself.

**Comment by tliron** [comment]
(Sorry, [insertMany](https://github.com/tliron/mongodb-jvm/blob/master/components/sincerity/libraries/scripturian/mongodb.js#L1540) specifically is what you need. I was just demonstrating that there are ...Many versions for each API.)
